Svidovyi task4
vserdun/java_enterprise pull request #24
Opened 2019-11-08 22:45 UTC by Svidic111

Bank Service Imitation

2019-11-12 13:46 UTC, vserdun requested changes

2019-11-12 13:46 UTC, vserdun commented on Oleksandr.Svidovyi/Task_4/src/main/java/configuration/BankAppConfig.java
> +    @Scope("singleton")
Scope singleton is not needed. It's default

2019-11-12 13:46 UTC, vserdun commented on Oleksandr.Svidovyi/Task_4/src/main/java/BankApp.java
> +        serviceManager = ctx.getBean("testServiceManager", TestServiceManager.class);
Use @Autowired instead of ctx.getBean

2019-11-12 13:46 UTC, vserdun commented on Oleksandr.Svidovyi/Task_4/src/main/java/BankApp.java
> +
Use @Autowired instead of ctx.getBean

2019-11-16 16:28 UTC, Svidic111 commented on Oleksandr.Svidovyi/Task_4/src/main/java/configuration/BankAppConfig.java
> +    @Scope("singleton")
deleted annotation

2019-11-16 16:28 UTC, Svidic111 commented on Oleksandr.Svidovyi/Task_4/src/main/java/BankApp.java
> +        serviceManager = ctx.getBean("testServiceManager", TestServiceManager.class);
Done

2019-11-16 16:28 UTC, Svidic111 commented on Oleksandr.Svidovyi/Task_4/src/main/java/BankApp.java
> +
Done

2019-11-18 10:16 UTC, merged